name: Build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up testcontainer ryuk:0.3.0
        run: docker image pull testcontainers/ryuk:0.3.0

      - name: Set up testcontainer dunalite:v1.2.1-1
        run: docker image pull quay.io/testcontainers/dynalite:v1.2.1-1

      - name: Unit and Integration tests
        run: mvn -B -Pit verify
